rpscalc/glossary/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Glossary views for RPS Calculator.
"""

from flask import Blueprint, render_template, session


mod = Blueprint('glossary', __name__, url_prefix='/glossary',
                static_folder='static', template_folder='templates')


@mod.route('/')
def glossary(definition=None):
    return render_template(
        'glossary.html',
        title='Glossary',
        # state=session['state'],
    )

rpscalc/state_comparison/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
State comparison views for RPS Calculator.
"""

from flask import Blueprint, render_template, session


mod = Blueprint('state_comparison', __name__, url_prefix='/comparison',
                template_folder='templates', static_folder='static')


@mod.route('/')
def comparison():
    state = session['state'] or False
    return render_template(
        'comparison.html',
        title='State by state RPS Comparison',
        state=state
    )


@mod.route('/trajectories')
def trajectories():
    state = session['state'] or False
    return render_template(
        'trajectories.html',
        title='State by state RPS Comparison',
        state=state
    )

rpscalc/state_pages/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
State page overviews for RPS Calculator.
"""

from flask import Blueprint, render_template, session, abort
from rpscalc.constants import RPS_STATES


mod = Blueprint('state_pages', __name__, url_prefix='/state',
                static_folder='static', template_folder='templates')


@mod.route('/<state>')
@mod.route('/<state>/')
def overview(state):
    if state == 'favicon.ico': abort(404)
    session['state'] = state
    return render_template(
        'overview_states/{}.html'.format(state),
        state=state,
        session_clear='true',
    )

rpscalc/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Base views for RPS Calculator. Index, and session update.
"""

from datetime import datetime
from flask import Blueprint, request, render_template, flash, g, session, \
    redirect, url_for, abort


mod = Blueprint('rpscalc', __name__, static_folder='static')


@mod.route('/update', methods=['POST',])
def update():
    try:
        for k, v in request.get_json(force=True).iteritems():
            session[k] = v
        return 'Session updated.'
    except:
        abort(500)


@mod.route('/')
def index():
    return render_template(
        'index.html',
        title='Renewable Portfolio Standards'
    )

@mod.route('/documentation')
def documentation():
    return render_template(
        'documentation.html',
    )

rpscalc/templates/_macros.html
{% macro calc_left_nav(state, page) %}
  {% for p in [
    ('trajectory', 'Set RPS trajectory'),
    ('carveouts', 'Set carveouts'),
    ('pricing', 'Set cost cap &amp; pricing'),
    ('cost', 'Projected cost'),
  ] %}
  <li{% if page==p[0] %} class="active"{% endif %}>
    <a href="{{ url_for('calculator.%s' % p[0], state=state) }}" data-name="{{ p[0] }}">
      {{ p[1]|safe }}
    </a></li>
  {% endfor %}
  <li class="left_nav_feature_link">
    <a href="{{ url_for('state_pages.overview', state=state) }}" class="offpage-link">
      Back to this state’s legislative overview
    </a></li>
  <li class="left_nav_feature_link">
    <a href="{{ url_for('state_comparison.comparison') }}" class="offpage-link">
      How does this state stack up?
    </a></li>
{% endmacro %}

rpscalc/templates/base.html
<!DOCTYPE html>
<!--[if lt IE 7]><html class="no-js lt-ie9 lt-ie8 lt-ie7"><![endif]-->
<!--[if IE 7]><html class="no-js lt-ie9 lt-ie8"><![endif]-->
<!--[if IE 8]><html class="no-js lt-ie9"><![endif]-->
<!--[if gt IE 8]><!--><html class="no-js"><!--<![endif]-->
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>RDCEP | RPS Calculator{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.css') }}?{{ now }}">
  {% block headcss %}
    {% assets 'css_main' %}<link rel="stylesheet" href="{{ ASSET_URL }}">{% endassets %}
  {% endblock %}
  <script src="{{ url_for('static', filename='js/vendor/modernizr.min.js') }}"></script>
</head>
<body>
  <!--[if lt IE 7]>
  <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
  <![endif]-->
{% block page %}{% endblock %}
{#  <script src="js/main.js"></script>#}
</body>
</html>

rpscalc/templates/base_page.html
{% extends 'base.html' %}
{% block title %} | {{ state|capitalize }}{% endblock %}
{% block headcss %}
  <link href="{{ url_for('static', filename='css/main.css') }}?{{ now }}" rel="stylesheet">
  <link href="{{ url_for('static', filename='css/map_styles.css') }}?{{ now }}" rel="stylesheet">
{% endblock %}
{% block page %}
  <header id="main_nav">
    <nav>
      <ul id="top_nav" class="clearfix">
        <li><a href="{{ url_for('rpscalc.index') }}">Home</a></li>
        <li class="menu-states" id="menu_states_overview">
          <a href="{{ url_for('state_pages.overview', state=state) }}">RPS Overview</a>
          <ul>
            {% for s in all_rps_states %}
            <li><a href="{{ url_for('state_pages.overview', state=s[0]) }}">{{ s[1]|safe }}</a></li>
            {% endfor %}
          </ul>
        </li>
        <li class="menu-states" id="menu_states_calculator">
          <a href="{{ url_for('calculator.trajectory', state=state) }}">Cost Calculator</a>
          <ul>
            {% for s in all_calc_states %}
            <li><a href="{{ url_for('calculator.trajectory', state=s[0]) }}">{{ s[1]|safe }}</a></li>
            {% endfor %}
          </ul>
        </li>
        <li><a href="/glossary">Glossary</a></li>
        <li><a href="/documentation">Documentation</a></li>
        {% if state %}<li id="menu_state_abbr">{{ state|state_abbr }}</li>{% endif %}
        <li><ul id="left_nav">
          {% block left_nav %}
          {% endblock %}
        </ul></li>
      </ul>
    </nav>
  </header>
  <article id="main_content">
  {% block content %}
    {% block header %}
      <section>
        <header>
          <h1>{{ title|replace('_', ' ')|title }}</h1>
        </header>
      </section>
    {% endblock %}
  {% endblock %}
  </article>
  <script>
    Options = window.Options || {};
    {%- block session_data -%}
    Options.data = {{ session|session_json|safe }};
    {%- endblock -%}
    Options.state = '{{ state }}';
    {% if state %}Options.state_abbr = '{{ state|state_abbr }}';{% endif %}
    Options.graph_type = '{{ graph_type }}';
  </script>
  {% block bodyjs %}
{#  <script src="//cdnjs.cloudflare.com/ajax/libs/d3/3.3.11/d3.min.js"></script>#}
    <script src="{{ url_for('static', filename='js/vendor/d3.v3.min.js') }}"></script>
  <script>
    window.d3 || document.write('<script src="{{ url_for('static', filename='js/vendor/d3.v3.min.js') }}"><\/script>')
  </script>
{#  <script src="//cdnjs.cloudflare.com/ajax/libs/json2/20121008/json2.js"></script>#}
    <script src="{{ url_for('static', filename='js/vendor/json2.js') }}"></script>
  <script>
    window.JSON || document.write('<script src="{{ url_for('static', filename='js/vendor/json2.js') }}"><\/script>')
  </script>
  {% assets 'js_main' %}
    <script src="{{ ASSET_URL }}"></script>
  {% endassets %}
  {% endblock %}
{% endblock %}

rpscalc/templates/base_state.html
{% extends 'base_page.html' %}
{% block title %} | {{ state|state_typo|safe }}{% endblock %}
{% block left_nav %}
  <li><a href data-name="snapshot" class="onpage-link">Snapshot</a></li>
  <li><a href data-name="energy" class="onpage-link">Energy Details</a></li>
  <li><a href data-name="legislation" class="onpage-link">Legislation</a></li>
  <li><a href data-name="resources" class="onpage-link">Resources</a></li>
  <li class="left_nav_feature_link">
    <a href="{{ url_for('calculator.trajectory', state=state) }}" class="offpage-link">
      Design the future of renewables in this state
    </a></li>
  <li class="left_nav_feature_link">
    <a href="{{ url_for('state_comparison.comparison') }}" class="offpage-link">
      How does this state stack up?
    </a></li>
{% endblock %}
{% block header %}
  <section>
    <header>
      <h1>{{ state|state_typo|safe }}</h1>
      <img src="{{ url_for('state_pages.static', filename='images/state_seals/' + state + '.png') }}" alt="State seal of {{ state|capitalize }}">
    </header>
  </section>
{% endblock %}

rpscalc/templates/documentation.html
{% extends 'base_page.html' %}
{% block title %} | Documentation{% endblock %}
{% block headcss %}
{{ super() }}
<style>
  #left_nav {display:none;}
  #main_content section {
    width: 960px;
    margin: 0;
  }
  #map {
    position: relative;
  }

  .state-options {
    height: 16px;
    width: 44px;
    padding: 3px 1px 6px 3px!important;
    background-color: black;
    position: absolute;
    display: none;
  }
  .option-icon {
    display: block;
    width: 16px;
    height: 16px;
    float: left;
    margin: 2px;
  }
  .state-overview-icon {
    background: url('/static/images/gui/rps_overview_16.png?1');
  }
  .state-calculator-icon {
    background: url('/static/images/gui/rps_calculator_16.png?1');
  }
</style>{% endblock %}
{% block content %}
{% block header %}
  <section>
    <header>
      <h1 style="">Documentation &amp; resources</h1>
    </header>
  </section>
{% endblock %}
  <section>
{#    <h2>RPS overview &amp; calculator</h2>#}
    <p>Documentation and resources are currently being compiled and will
      appear here shortly. We apologize for the delay.</p>
  </section>
{% endblock %}

rpscalc/templates/index.html
{% extends 'base_page.html' %}
{% block headcss %}
{{ super() }}
<style>
  #left_nav {display:none;}
  #main_content section {
    width: 960px;
    margin: 0;
  }
  #map {
    position: relative;
  }

  .state-options {
    height: 16px;
    width: 44px;
    padding: 3px 1px 6px 3px!important;
    background-color: black;
    position: absolute;
    display: none;
  }
  .option-icon {
    display: block;
    width: 16px;
    height: 16px;
    float: left;
    margin: 2px;
  }
  .state-overview-icon {
    background: url('/static/images/gui/rps_overview_16.png?1');
  }
  .state-calculator-icon {
    background: url('/static/images/gui/rps_calculator_16.png?1');
  }
</style>{% endblock %}
{% block content %}
{% block header %}
  <section>
    <header>
      <h1 style="">{{ title|replace('_', ' ') }}</h1>
    </header>
  </section>
{% endblock %}
  <section>
    <h2>RPS overview &amp; calculator</h2>
    <p>Welcome to RDCEP’s <a href="{{ url_for('glossary.glossary') }}#rps">renewable
      portfolio standard (RPS)</a> portal! Twenty-nine states plus Washington
      D.C. have enacted an RPS into law, as represented by the map below.
      Using the information and tools presented on this site, you can learn
      what an RPS is and how it is implemented in your state. Each policy is
      a little bit different: click on a state on the map to learn more about
      its particular policy. Once you are familiar with your state’s policy,
      visit the RPS Feasibility Calculator to see how the specifics of your
      state’s policy can affect its success.</p>
  </section>
  <div id="map"></div>
{% endblock %}
{% block bodyjs %}
{{ super() }}
<script src="{{ url_for('static', filename='js/vendor/d3.geo.projection.v0.min.js') }}?2"></script>
<script src="{{ url_for('static', filename='js/vendor/topojson.v1.min.js') }}?2"></script>
<script src="{{ url_for('static', filename='js/home_map.js') }}?2"></script>
{% endblock %}

rpscalc/templates/state.html
{% extends 'base_page.html' %}
{% block title %} | {{ state|capitalize }}{% endblock %}
{% block left_nav %}
  <li><a href data-name="snapshot" class="onpage-link">Snapshot</a></li>
  <li><a href data-name="energy" class="onpage-link">Energy Details</a></li>
  <li><a href data-name="legislation" class="onpage-link">Legislation</a></li>
  <li><a href data-name="resources" class="onpage-link">Resources</a></li>
  <li id="left_nav_calculator_link">
    <a href="{{ url_for('calculator.trajectory', state=state) }}" class="offpage-link">
      Design your own renewables future
    </a></li>
  <li id="left_nav_comparison_link">
    <a href="{{ url_for('state_comparison.comparison') }}" class="offpage-link">
      State Comparisons
    </a></li>
{% endblock %}
{% block header %}
  <section>
    <header>
      <h1>{{ state|replace('_', ' ')|title }}</h1>
      <img src="{{ url_for('static', filename='images/state_seals/' + state + '.png') }}" alt="State seal of {{ state|capitalize }}">
    </header>
  </section>
{% endblock %}