rpscalc/calculator/views.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Calculator views for RPS Calculator.
"""

from flask import Blueprint, request, render_template, flash, g, session, \
    redirect, url_for, abort
from rpscalc.constants import RPS_STATES


mod = Blueprint('calculator', __name__, url_prefix='/calculator',
                static_folder='static', template_folder='templates')


def state_without_calculator(state):
    return not [s.calculator for k, s in RPS_STATES.iteritems() if s.names[0] == state][0]


def update_calc_state(state):
    print session['state']
    for k in ['trajectory', 'wind', 'solar', 'rps', 'price_and_policy']:
        session[k] = False
    if state != session['state']:
        session['state'] = state


@mod.route('/clear', methods=['POST',])
def clear():
    try:
        for k, v in request.get_json(force=True).iteritems():
            if k in ['trajectory', 'wind', 'solar', 'rps', 'price_and_policy']:
                session[k] = False
            else:
                session[k] = v
        session['clear'] = False
        return 'Session cleared.'
    except:
        abort(500)


@mod.route('/update', methods=['POST',])
def update():
    try:
        for k, v in request.get_json(force=True).iteritems():
            session[k] = v
        session['clear'] = False
        return 'Session updated.'
    except:
        abort(500)


@mod.route('/<state>/trajectory')
def trajectory(state):
    if state_without_calculator(state):
        return render_template(
            'no_calculator.html',
            state=state,
        )
    return render_template(
        'trajectory_states/{}.html'.format(state),
        state=state,
        session_clear=False if state == session['state'] else True,
    )


@mod.route('/<state>/carveout')
def carveouts(state):
    if state_without_calculator(state):
        return render_template(
            'no_calculator.html',
            state=state,
        )
    if 'trajectory' not in session.keys():
        return redirect(url_for('calculator.trajectory', state=state))
    return render_template(
        'carveout_states/{}.html'.format(state),
        state=session['state'] or state,
    )


@mod.route('/<state>/pricing')
def pricing(state):
    if state_without_calculator(state):
        return render_template(
            'no_calculator.html',
            state=state,
        )
    if not session['trajectory']:
        return redirect(url_for('calculator.trajectory', state=state))
    if not session['wind'] or not session['solar']:
        return redirect(url_for('calculator.carveouts', state=state))
    return render_template(
        'pricing_states/{}.html'.format(state),
        state=session['state'] or state,
    )

@mod.route('/<state>/cost')
def cost(state):
    if state_without_calculator(state):
        return render_template(
            'no_calculator.html',
            state=state,
        )
    if not session['trajectory']:
        return redirect(url_for('calculator.trajectory', state=state))
    if not session['wind'] or not session['solar']:
        return redirect(url_for('calculator.carveouts', state=state))
    if not session['price_and_policy']:
        return redirect(url_for('calculator.pricing', state=state))
    return render_template(
        'cost_states/{}.html'.format(state),
        state=session['state'] or state,
    )

@mod.route('/<state>/advanced')
def advanced(state):
    if state_without_calculator(state):
        return render_template(
            'no_calculator.html',
            state=state,
        )
    if not session['trajectory']:
        return redirect(url_for('calculator.trajectory', state=state))
    if not session['wind'] or not session['solar']:
        return redirect(url_for('calculator.carveouts', state=state))
    if not session['price_and_policy']:
        return redirect(url_for('calculator.pricing', state=state))
    return render_template(
        'advanced.html',
        state=session['state'] or state,
    )

rpscalc/calculator/templates/carveout_states/california.html
{% extends 'carveouts.html' %}
{% block state_specific %}
  California’s RPS does not have any carve-outs; however, you can add your
  own requirements by typing in the boxes and adjusting the graph below.
{% endblock %}

rpscalc/calculator/templates/carveout_states/colorado.html
{% extends 'carveouts.html' %}
{% block state_specific %}
  Colorado’s RPS has a carve-out for customer-sited distributed generation
  technology, at 3% of the RPS requirement. Because the RPS calculator
  currently supports carve-outs for only wind and solar power, you can
  try experimenting with these technology requirements by adding values
  to the graph below.
{% endblock %}

rpscalc/calculator/templates/carveout_states/iowa.html
{% extends 'carveouts.html' %}
{% block state_specific %}
  Iowa’s RPS does not have any carve-outs; however, you can add your own
  requirements by typing in the boxes and adjusting the graph below.
{% endblock %}

rpscalc/calculator/templates/carveout_states/maine.html
{% extends 'carveouts.html' %}
{% block state_specific %}
  Maine’s RPS does not have any technology-specific carve-outs;
  however, you can add your own requirements by typing in the boxes and
  adjusting the graph below.
{% endblock %}

rpscalc/calculator/templates/carveout_states/maryland.html
{% extends 'carveouts.html' %}
{% block state_specific %}
  Maryland’s RPS is divided into two tiers of generation with their
  own requirements in each year: solar—2% by 2020, offshore
  wind—yet to be finalized.
{% endblock %}

rpscalc/calculator/templates/carveout_states/massachusetts.html
{% extends 'carveouts.html' %}
{% block state_specific %}
  Massachusett’s has a capacity-based solar requirement of 400 MW
  that begins in 2010.
{% endblock %}

rpscalc/calculator/templates/carveout_states/minnesota.html
{% extends 'carveouts.html' %}
{% block state_specific %}
  Minnesota’s RPS requires all public utilities achieve 1.5% solar energy
  by 2020. There is a separate requirement for Xcel Energy for 24% wind
  energy by 2020.
{% endblock %}

rpscalc/calculator/templates/carveout_states/missouri.html
{% extends 'carveouts.html' %}
{% block state_specific %}
  Missouri’s RPS has a carve-out for solar electric of 2% of the
  annual requirement.
{% endblock %}

rpscalc/calculator/templates/carveout_states/montana.html
{% extends 'carveouts.html' %}
{% block state_specific %}
  Montana’s RPS does not have any technology-specific carve-outs;
  however, you can add your own requirements by typing in the boxes and
  adjusting the graph below.
{% endblock %}

rpscalc/calculator/templates/carveout_states/nevada.html
{% extends 'carveouts.html' %}
{% block state_specific %}
  Nevada states that 5% of the annual RPS requirement be fulfilled through
  solar until 2016. For the period 2016 to 2025, it rises to 6% of generation.
{% endblock %}

rpscalc/calculator/templates/carveout_states/new_mexico.html
{% extends 'carveouts.html' %}
{% block state_specific %}
  New Mexico has a diverse set of carve-outs. Of the annual RPS requirement,
  30% must be from wind, and 20% from solar. Other smaller carve-outs
  include geothermal, hydro, and distributed generation.
{% endblock %}

rpscalc/calculator/templates/carveout_states/new_york.html
{% extends 'carveouts.html' %}
{% block state_specific %}
{% endblock %}

rpscalc/calculator/templates/carveout_states/washington.html
{% extends 'carveouts.html' %}
{% block state_specific %}
  Washington’s RPS does not have any carve-outs; however, you can add your
  own requirements by typing in the boxes and adjusting the graph below.
{% endblock %}

rpscalc/calculator/templates/carveout_states/wisconsin.html
{% extends 'carveouts.html' %}
{% block state_specific %}
  Wisconsin’s RPS does not have any carve-outs; however, you can add your
  own requirements by typing in the boxes and adjusting the graph below.
{% endblock %}

rpscalc/calculator/templates/carveouts.html
{% extends 'base_state.html' %}
{% import '_macros.html' as macros %}
{% block title %} | {{ state|capitalize }}{% endblock %}
{% block left_nav %}
  {{ macros.calc_left_nav(state, 'carveouts') }}
{% endblock %}
{% block content %}
  {{ super() }}
  <section class="clearfix">

    <h2>Carveouts</h2>

    <p>Now that you have chosen your state’s
      <a href="{{ url_for('glossary.glossary') }}#rps_trajectory">RPS trajectory</a>,
      you have the opportunity to define which technologies your state will
      use to fulfill its goals. Some states establish these
      <a href="{{ url_for('glossary.glossary') }}#technology_requirement">technology
      requirements</a> by establishing individual ‘sub-trajectories’, or
      <a href="{{ url_for('glossary.glossary') }}#technology_requirement">carve-outs</a>,
      for each renewable source they wish to promote. The
      RPS Calculator allows you to set minimum requirements for wind
      and solar power as a percentage of the total RPS goal that was
      set on the previous screen). {% block state_specific %}{% endblock %}
      It is important to keep in mind that requiring specific technologies
      can impact the overall cost of your policy.</p>

    <div id="carveouts" class="module clearfix chart-outer-wrap">
    </div>

    <p>To edit or create new minimum technology requirements for your
      state, click and drag the blue and yellow areas. Blue represents
      the portion of the RPS goal that must be fulfilled with solar
      energy, while yellow represents wind power. You can only create
      carve-outs that sum to 100% of your RPS, so in a given year, you
      may need to decrease the amount of one technology before you can
      increase the amount of the other.</p>
    <p>If you would rather type in your values, toggle-on the user
      input boxes by clicking ‘type’ on top of the graph. If you would
      like to require your state to satisfy more than 50% of its
      requirement using wind or solar, change the graph’s scale from
      50% to 100% by clicking ‘100’ on top of the graph.</p>

    <ul id="crumbs">
      <li id="crumb_trajectory"><a href="{{ url_for('calculator.trajectory', state=state) }}">Trajectory</a>
      <li id="crumb_carveouts" class="active"><a href="{{ url_for('calculator.carveouts', state=state) }}">Carveouts</a></li>
      <li id="crumb_pricing"><a href="{{ url_for('calculator.pricing', state=state) }}">Cost cap &amp; Pricing</a></li>
      <li id="crumb_cost" class="disabled"><a>Projected Cost</a></li>
    </ul>
  </section>
{% endblock %}
{% block bodyjs %}
  {{ super() }}
  {% assets 'js_carveouts' %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
{% endblock %}

rpscalc/calculator/templates/cost.html
{% extends 'base_state.html' %}
{% import '_macros.html' as macros %}
{% block title %} | {{ state|capitalize }}{% endblock %}
{% block left_nav %}
  {{ macros.calc_left_nav(state, 'cost') }}
{% endblock %}
{% block content %}
  {{ super() }}
  <section class="clearfix">

    <h2>Cost cap and pricing</h2>

    <p>You have now established the fundamental design of your RPS.
      On this page you will test the efficacy of your policy by estimating
      how much renewable energy will be provided in your state before you
      hit the cost cap. The blue region represents the cost of the mean
      <a href="{{ url_for('glossary.glossary') }}#rec">Renewable Energy
      Credit (REC)</a>, in dollars per megawatt-hour, calculated based on
      your state’s policy or the policy you created. The orange region
      represents REC values, in dollars per megawatt-hour, prohibited by
      the cost cap you imposed. Any cross-hatched region that appears
      represents time periods in which you have ‘broken’ your cost cap,
      at which point your RPS requirements are placed on a ‘freeze.’</p>
    <p>Was your policy successful for its entire duration? If not, don’t
      worry! On this page, you can explore the interactions of the major
      components of an RPS. Try changing some of your policy’s
      characteristics, like its trajectory or carve-outs, to see how
      they affect the overall goal and the cost of meeting this goal.</p>

    <div class="chart-outer-wrap">
      <div id="cost_chart" class="module clearfix"></div>
      <div id="chart_wrap" class="module clearfix" style="width:730px; left:-30px; position: relative;">

        <form class="clearfix" id="chart_inputs">

          <div id="time_series_wrap"></div>

          <!-- append -->
          <div class="chart-input-row">
            <div class="chart-input-pp-wrap" style="width: 166.59977452085684px; float: left;">
              <h5>Policy</h5>
              <div class="clearfix chart-input-row chart-input-pp">
                <label>
                  <input class="chart-input" type="checkbox" data-type="PTC" name="policy_ptc">
                  <div style="width: 113.44983089064263px; float: left;">PTC</div>
                </label>
              </div>
              {% block state_costcap %}
                <div class="clearfix chart-input-row chart-input-pp">
                  <label>
                    <input class="chart-input" type="text" data-type="Cost cap" name="policy_costcap">
                    <div style="width: 113.44983089064263px; float: left;">Cost cap (%)</div>
                  </label>
                </div>
              {% endblock %}
            </div>
            <div class="chart-input-pp-wrap" style="width: 166.59977452085684px; float: left;">
              <h5>Financing</h5>
              <div class="clearfix chart-input-row chart-input-pp">
                <label>
                  <input class="chart-input" type="text" data-type="Contract term" name="finance_contractterm">
                  <div style="width: 113.44983089064263px; float: left;">Contract term (yr)</div>
                </label>
              </div>
              <div class="clearfix chart-input-row chart-input-pp">
                <label>
                  <input class="chart-input" type="text" data-type="Interest rate" name="finance_interestrate">
                  <div style="width: 113.44983089064263px; float: left;">Interest rate (%)</div>
                </label>
              </div>
            </div>
            <div class="chart-input-pp-wrap" style="width: 166.59977452085684px; float: left;">
              <h5>Price</h5>
              <div class="clearfix chart-input-row chart-input-pp">
                <label>
                  <input class="chart-input" type="text" data-type="Wholesale price" name="pricing_wholesale">
                  <div style="width: 113.44983089064263px; float: left;">Wholesale price ($)</div>
                </label>
              </div>
              <div class="clearfix chart-input-row chart-input-pp">
                <label>
                  <input class="chart-input" type="text" data-type="Annual growth" name="pricing_annualgrowth">
                  <div style="width: 113.44983089064263px; float: left;">Annual growth (%)</div>
                </label>
              </div>
            </div>
          </div>
      </form>

      </div>

    </div>

    <p>The values you chose at the beginning of this calculator are
      entered in the boxes. Try adjusting column values individually
      to see the effect on the overlapping region. Refer back to the Cost
      Cap &amp; Pricing slide to review or adjust assumptions about the
      cost of wind and solar power, and the other parameters that play
      into the success of your RPS.</p>

    <ul id="crumbs">
      <li id="crumb_trajectory"><a href="{{ url_for('calculator.trajectory', state=state) }}">Trajectory</a>
      <li id="crumb_carveouts"><a href="{{ url_for('calculator.carveouts', state=state) }}">Carveouts</a></li>
      <li id="crumb_pricing"><a href="{{ url_for('calculator.pricing', state=state) }}">Cost cap &amp; Pricing</a></li>
      <li id="crumb_cost" class="active"><a href="{{ url_for('calculator.cost', state=state) }}">Projected Cost</a></li>
    </ul>
  </section>
{% endblock %}
{% block bodyjs %}
  {{ super() }}
{#  <script src="{{ url_for('calculator.static', filename='js/advanced.js') }}"></script>#}
  {% assets 'js_cost' %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
{% endblock %}

rpscalc/calculator/templates/cost_states/colorado.html
{% extends 'cost.html' %}
{% block state_specific %}
{% endblock %}
{% block state_costcap %}
  <div class="clearfix chart-input-row chart-input-pp">
    <label>
      <input class="chart-input" type="text" data-type="Cost cap" name="policy_costcap">
      <div>Cost cap (%)</div>
    </label>
  </div>
{% endblock %}

rpscalc/calculator/templates/cost_states/illinois.html
{% extends 'cost.html' %}
{% block state_specific %}
{% endblock %}
{% block state_costcap %}
  <div class="clearfix chart-input-row chart-input-pp">
    <label>
      <input class="chart-input" type="text" data-type="Cost cap" name="policy_costcap">
      <div>Cost cap (%)</div>
    </label>
  </div>
{% endblock %}

rpscalc/calculator/templates/cost_states/kansas.html
{% extends 'cost.html' %}
{% block state_specific %}
{% endblock %}

rpscalc/calculator/templates/cost_states/maine.html
{% extends 'cost.html' %}
{% block state_specific %}
{% endblock %}

rpscalc/calculator/templates/cost_states/massachusetts.html
{% extends 'cost.html' %}
{% block state_specific %}
{% endblock %}
{% block state_costcap %}
  <div class="clearfix chart-input-row chart-input-pp">
    <label>
      <input class="chart-input" type="text" data-type="Cost cap" name="policy_acp">
      <div>ACP ($)</div>
    </label>
  </div>
{% endblock %}

rpscalc/calculator/templates/cost_states/missouri.html
{% extends 'cost.html' %}
{% block state_specific %}
{% endblock %}
{% block state_costcap %}
  <div class="clearfix chart-input-row chart-input-pp">
    <label>
      <input class="chart-input" type="text" data-type="Cost cap" name="policy_costcap">
      <div>Cost cap (%)</div>
    </label>
  </div>
{% endblock %}

rpscalc/calculator/templates/cost_states/montana.html
{% extends 'cost.html' %}
{% block state_specific %}
{% endblock %}
{% block state_costcap %}
{% endblock %}

rpscalc/calculator/templates/cost_states/new_mexico.html
{% extends 'cost.html' %}
{% block state_specific %}
{% endblock %}
{% block state_costcap %}
{% endblock %}

rpscalc/calculator/templates/cost_states/new_york.html
{% extends 'cost.html' %}
{% block state_specific %}
{% endblock %}
{% block state_costcap %}
{% endblock %}

rpscalc/calculator/templates/cost_states/ohio.html
{% extends 'cost.html' %}
{% block state_specific %}
{% endblock %}
{% block state_costcap %}
{% endblock %}

rpscalc/calculator/templates/cost_states/oregon.html
{% extends 'cost.html' %}
{% block state_specific %}
{% endblock %}
{% block state_costcap %}
{% endblock %}

rpscalc/calculator/templates/cost_states/rhode_island.html
{% extends 'cost.html' %}
{% block state_specific %}
{% endblock %}
{% block state_costcap %}
  <div class="clearfix chart-input-row chart-input-pp">
    <label>
      <input class="chart-input" type="text" data-type="Cost cap" name="policy_acp">
      <div>ACP ($)</div>
    </label>
  </div>
{% endblock %}

rpscalc/calculator/templates/cost_states/texas.html
{% extends 'cost.html' %}
{% block state_specific %}
{% endblock %}
{% block state_costcap %}
  <div class="clearfix chart-input-row chart-input-pp">
    <label>
      <input class="chart-input" type="text" data-type="Cost cap" name="policy_acp">
      <div>ACP ($)</div>
    </label>
  </div>
{% endblock %}

rpscalc/calculator/templates/cost_states/wisconsin.html
{% extends 'cost.html' %}
{% block state_specific %}
{% endblock %}
{% block state_costcap %}
{% endblock %}

rpscalc/calculator/templates/no_calculator.html
{% extends 'base_state.html' %}
{% import '_macros.html' as macros %}
{% block title %} | {{ state|capitalize }}{% endblock %}
{% block left_nav %}
  {{ macros.calc_left_nav(state, None) }}
{% endblock %}
{% block content %}
  {{ super() }}
  <section class="clearfix">

    <h2>Calculator unavailable</h2>

    <p>Unfortunately, the RPS calculator for {{ state|state_typo }}
      isn’t yet finalized. Please try another state, or check back at a
    later date.</p>

  </section>
{% endblock %}

rpscalc/calculator/templates/pricing.html
{% extends 'base_state.html' %}
{% import '_macros.html' as macros %}
{% block title %} | {{ state|capitalize }}{% endblock %}
{% block left_nav %}
  {{ macros.calc_left_nav(state, 'pricing') }}
{% endblock %}
{% block content %}
  {{ super() }}
  <section class="clearfix">

    <h2>Cost cap and pricing</h2>

    <p>The success of your RPS will not only depend on the trajectory
      and carve-outs you have just selected, but also on renewable
      technology costs, electricity costs, federal energy policy
      and the RPS <a href="{{ url_for('glossary.glossary') }}#cost_cap">cost cap</a>.
      While you can adjust several parameters
      that impact cost on this page, the cost cap is the only policy
      instrument implemented by the state. Lawmakers use this device
      in their RPS  to protect electricity customers from potential rate
      increases as a result of using more expensive renewable electricity
      sources. For some states, this cost cap could limit the total
      amount of renewable power that will be purchased to fulfill the
      RPS goals.</p>
    <p>{% block state_specific %}{% endblock %}</p>
    <p>On this page you can establish your own cost cap, as well as
      adjust the default assumptions about retail electricity rates and
      the cost of renewable power.</p>

    <div id="pricing" class="module clearfix chart-outer-wrap">
      <form id="pricing_form">
        <div class="narrow module">

          <fieldset id="policy_parameters" class="narrow" style="clear:left;">
            <h4>Policy parameters</h4>
            {% block state_policy %}
            <div class="clearfix">
              <label for="policy_costcap">Cost cap (%)</label>
              <input type="text" id="policy_costcap" name="policy_costcap" pattern="[0-9]*\.*[0-9]+">
            </div>
            {% endblock %}
            <div class="clearfix">
              <label for="policy_ptc">PTC</label>
              <input type="checkbox" id="policy_ptc" name="policy_ptc" checked>
            </div>
          </fieldset>

          <fieldset id="policy_costs" class="narrow">
            <h4>Pricing parameters</h4>
            <div class="clearfix visuallyhidden">
              <label for="policy_retail">Retail ($/MWh)</label>
              <input type="text" id="policy_retail" name="policy_retail" pattern="[0-9]*\.*[0-9]+">
            </div>
            <div class="clearfix">
              <label for="pricing_wholesale">Wholesale ($/MWh)</label>
              <input type="text" id="pricing_wholesale" name="pricing_wholesale" pattern="[0-9]*\.*[0-9]+">
            </div>
            <div class="clearfix">
              <label for="pricing_annualgrowth">Annual growth (%)</label>
              <input type="text" id="pricing_annualgrowth" name="pricing_annualgrowth" pattern="[0-9]*\.*[0-9]+">
            </div>
          </fieldset>

          <fieldset id="policy_financing" class="narrow">
            <h4>Financing parameters</h4>
            <div class="clearfix">
              <label for="finance_contractterm">Contract Term (yrs)</label>
              <input type="text" id="finance_contractterm" name="finance_contractterm" pattern="[0-9]*\.*[0-9]+">
            </div>
            <div class="clearfix">
              <label for="finance_interestrate">Interest Rate (%)</label>
              <input type="text" id="finance_interestrate" name="finance_interestrate" pattern="[0-9]*\.*[0-9]+">
            </div>
          </fieldset>
        </div>
        <div class="narrow module">

          <fieldset id="wind_costs" class="narrow">
            <h4>Wind parameters</h4>
            <div class="clearfix">
              <label for="wind_capacity">Capacity factor</label>
              <input type="text" id="wind_capacity" name="wind_capacity" pattern="[0-9]*\.*[0-9]+">
            </div>
            <div class="clearfix">
              <label for="wind_installation">Installation ($/W)</label>
              <input type="text" id="wind_installation" name="wind_installation" pattern="[0-9]*\.*[0-9]+">
            </div>
            <div class="clearfix">
              <label for="wind_om">O &amp; M ($/MWh)</label>
              <input type="text" id="wind_om" name="wind_om" pattern="[0-9]*\.*[0-9]+">
            </div>
            <div class="clearfix">
              <label for="wind_integration">Integration ($/MWh)</label>
              <input type="text" id="wind_integration" name="wind_integration" pattern="[0-9]*\.*[0-9]+">
            </div>
          </fieldset>

          <fieldset id="solar_costs" class="narrow">
            <h4>Solar parameters</h4>
            <div class="clearfix">
              <label for="solar_capacity">Capacity factor</label>
              <input type="text" id="solar_capacity" name="solar_capacity" pattern="[0-9]*\.*[0-9]+">
            </div>
            <div class="clearfix">
              <label for="solar_installation">Installation ($/W)</label>
              <input type="text" id="solar_installation" name="solar_installation" pattern="[0-9]*\.*[0-9]+">
            </div>
            <div class="clearfix">
              <label for="solar_om">O &amp; M ($/MWh)</label>
              <input type="text" id="solar_om" name="solar_om" pattern="[0-9]*\.*[0-9]+">
            </div>
          </fieldset>
        </div>
      </form>
      <div class="narrow module" style="margin:1em 0 0 6px;padding-left:20px;width:300px">
        <p><b>Wind cost:</b> <span id="wind_cost"></span></p>
        <p><b>Solar cost:</b> <span id="solar_cost"></span></p>
      </div>
    </div>

    <p>The default values entered in the boxes are based on conservative
      estimates from reliable sources. Wind and solar costs are national
      values and do not vary across regions, while
      <a href="{{ url_for('glossary.glossary') }}#capacity_factor">capacity
      factors</a> are state-specific. You may choose to deselect the
      <a href="{{ url_for('glossary.glossary') }}#ptc">Production Tax
      Credit</a> policy to create a scenario in which renewable technologies
      are unsubsidized. The cost cap parameter default value is that of
      your state; if your state does not have a cost cap, 3% may be a
      good starting point.</p>

    <ul id="crumbs">
      <li id="crumb_trajectory"><a href="{{ url_for('calculator.trajectory', state=state) }}">Trajectory</a>
      <li id="crumb_carveouts"><a href="{{ url_for('calculator.carveouts', state=state) }}">Carveouts</a></li>
      <li id="crumb_pricing" class="active"><a href="{{ url_for('calculator.pricing', state=state) }}">Cost cap &amp; Pricing</a></li>
      <li id="crumb_cost"><a href="{{ url_for('calculator.cost', state=state) }}">Projected Cost</a></li>
    </ul>
  </section>
{% endblock %}
{% block bodyjs %}
  {{ super() }}
  {% assets 'js_pricing' %}<script src="{{ ASSET_URL }}"></script>{% endassets %}
{% endblock %}

rpscalc/calculator/templates/pricing_states/colorado.html
{% extends 'pricing.html' %}
{% block state_specific %}
  Colorado has an explicit <a href="{{ url_for('glossary.glossary') }}#cost_cap">cost cap</a>,
  which seeks to protect its residents from electricity rate increases by
  limiting the cost of the policy to a specified percentage over of the
  average customer's bill. The RPS can be adjusted and/or frozen by the PUC
  if the cost of the policy exceeds the cap.
{% endblock %}
{% block state_policy %}
  <input type="hidden" id="policy_captype" name="policy_captype" value="retail">
  <div class="clearfix">
    <label for="policy_costcap">Cost cap (%)</label>
    <input type="text" id="policy_costcap" name="policy_costcap" pattern="[0-9]*\.*[0-9]+">
  </div>
{% endblock %}

rpscalc/calculator/templates/pricing_states/hawaii.html
{% extends 'pricing.html' %}
{% block state_specific %}
  Hawai‘i does not have an explicit cost cap. However, the Public
  Utilities Commission (PUC) may waive compliance with the RPS program for
  good cause.
{% endblock %}
{% block state_policy %}
  <input type="hidden" id="policy_captype" name="policy_captype" value="none">
{% endblock %}

rpscalc/calculator/templates/pricing_states/maryland.html
{% extends 'pricing.html' %}
{% block state_specific %}
{% endblock %}
{% block state_policy %}
  <input type="hidden" id="policy_captype" name="policy_captype" value="single-acp">
  <div class="clearfix">
    <label for="policy_costcap">ACP ($)</label>
    <input type="text" id="policy_acp" name="policy_acp" pattern="[0-9]+\.*[0-9]*">
  </div>
{% endblock %}

rpscalc/calculator/templates/pricing_states/michigan.html
{% extends 'pricing.html' %}
{% block state_specific %}
  Michigan has an explicit <a href="{{ url_for('glossary.glossary') }}#cost_cap">cost cap</a>,
  which seeks to protect its residents from electricity rate increases by
  limiting the cost of the policy to a specified dollar value over the
  average customer's bill.
{% endblock %}
{% block state_policy %}
  <input type="hidden" id="policy_captype" name="policy_captype" value="retail-dollar">
  <div class="clearfix">
    <label for="policy_costcap">Cost cap ($ / monthly bill)</label>
    <input type="text" id="policy_costcap" name="policy_costcap" pattern="[0-9]+\.*[0-9]\*">
  </div>
{% endblock %}